### ISSUE TITLE
Add option to disable animation on initial load

### ISSUE THREAD

**Issue by trajano** [cyberthom/react-slide-animation#1]
Is it possible to set it such that the animation does not trigger when initially loading the page?

**Comment by thomheymann** [comment]
The animation is not triggered on initial render as this module only uses `componentWillEnter` and `componentWillLeave` (but not `componentWillAppear`). See https://github.com/reactjs/react-transition-group#componentwillenter for more info.

Do you have a test case to reproduce the issue?

**Comment by trajano** [comment]
https://trajano.github.io/reactjs-admin but I think it's fine based on how you describe it.  It does the animation when I switch from xs (really small window size to trigger the sidenav appear) and sm and higher mode.

**Comment by trajano** [comment]
Closing for now.
